name: Run Tests

on: [push, pull_request]

jobs:

  test:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v2
      with:
          submodules: true

    - name: Install latest PHPUnit
      run: wget https://phar.phpunit.de/phpunit-10.5.20.phar

    - name: Run Tests
      run: phpdbg -qrr phpunit.phar tests/SonosTest.php --configuration tests/phpunit.xml
      